// USER AUTH
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const CLEAR_REGISTER = "CLEAR_REGISTER";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const FETCH_USER = "FETCH_USER";
export const USER_UPDATE = "USER_UPDATE";
export const CLEAN_USER_INFO = "CLEAN_USER_INFO";
export const FETCH_ORDERS = "FETCH_ORDERS";

export const FETCH_BANNERS = "FETCH_BANNERS"

export const FETCH_SECTION_PRODUCTS = "FETCH_SECTION_PRODUCTS"

export const FETCH_BRANDS ="FETCH_BRANDS"

export const ADD_TO_CART = "ADD_TO_CART"

export const FETCH_CART ="FETCH_CART"

export const DELETE_FROM_CART = "DELETE_FROM_CART"

export const TOGGLE_FAVOURITE = "TOGGLE_FAVOURITE"

export const FETCH_COMPARE ="FETCH_COMPARE"

export const FETCH_COMPARE_CLASSES = "FETCH_COMPARE_CLASSES"

export const TOGGLE_COMPARE = "TOGGLE_COMPARE"

export const FETCH_FAVOURITES ="FETCH_FAVOURITES"

export const FETCH_CATEGORY_PRODUCTS ="FETCH_CATEGORY_PRODUCTS"

export const FETCH_CATEGORIES = "FETCH_CATEGORIES"

export const CLEAR_FILTER_CAT_PRODUCTS ="CLEAR_FILTER_CAT_PRODUCTS"

export const  CLEAR_SEARCH = "CLEAR_SEARCH"

export const GET_SEARCH = "GET_SEARCH"

export const FETCH_DELIVERY_TYPES = "FETCH_DELIVERY_TYPES"
export const FETCH_PAYMENT_TYPES = "FETCH_PAYMENT_TYPES"
export const FETCH_CITIES = "FETCH_CITIES"
export const MAKE_ORDER = "MAKE_ORDER"

export const FETCH_USER_INFO = "FETCH_USER_INFO"
export const FETCH_USER_ADDRESSES = "FETCH_USER_ADDRESSES"
export const FETCH_USER_ORDERS = "FETCH_USER_ORDERS"

export const FETCH_USER_ORDER = "FETCH_USER_ORDER"

export const GENERATE_CODE ="GENERATE_CODE"
export const VERIFY_PHONE = "VERIFY_PHONE"
export const UPDATE_CODE = "UPDATE_CODE"
export const AUTH_PASS_FORGOT = "AUTH_PASS_FORGOT"
export const UPDATE_USER_INFO = "UPDATE_USER_INFO"

export const FETCH_FILTERS = "FETCH_FILTERS"

export const CHANGE_MAIN_ADDR = "CHANGE_MAIN_ADDR"
export const DELETE_FROM_ADDRESS = "SDELETE_FROM_ADDRESS"
export const CHANGE_MAIN_USER_ADDRESS = "CHANGE_MAIN_USER_ADDRESS"

export const UPDATE_PARTNER_WITH_PAYMENT_CART = "UPDATE_PARTNER_WITH_PAYMENT_CART"
export const UPDATE_PARTNER_CART = "UPDATE_PARTNER_CART"