;
export const popularCategory = [
    {
        id: 0,
        title: 'Телефоны и планшеты',
        uzTitle: 'Telefonlar va planshetlar',
        className: "iPad",
        img: '/first.png',
        href: "/catalog/telefony-i-plansheti",
    },
    {
        id: 1,
        title: 'Товары для офиса',
        uzTitle: 'Ofis uchun tovarlar',
        className: "monoBlocks",
        img:"/first2.png",
        href: "/catalog/tekhnika-dlya-ofisa",
    },
    {
        id: 2,
        title: 'Оргтехника',
        uzTitle: 'Tashkiliy texnika',
        className: "officeEquipment",
        img: '/first3.png',
        href: "/catalog/orgtekhnika",
    },
    {
        id: 3,
        title: 'Aксессуары',
        uzTitle: 'Aksessuarlar',
        className: "accessories",
        img: "/first4.png",
        href: "catalog/sotovye-telefony-i-aksessuary",
    },
    
    {
        id: 4,
        title: 'Для геймеров',
        uzTitle: 'Geymerlar uchun',
        className: "forGamers",
        img: "/first5.png",
        href: "/catalog/dlya-geymerov",
    },
    {
        id: 5,
        title: 'Ноутбуки',
        uzTitle: 'Noutbuklar',
        img:"/first6.png",
        className: "laptops",
        href: "/catalog/noutbuki-2",
    },
    {
        id: 6,
        title: 'Компьютеры',
        uzTitle: 'Kompyuterlar',
        img:"/first7.png",
        className: "computers",
        href: "/catalog/kompyutery",
    },
    {
        id: 7,
        title: 'Техника для дома',
        uzTitle: 'Uy uchun Texnikalar',
        img:"/first8.png",
        className: "cctv",
        href: "/catalog/tekhnika-dlya-doma",
    },
    {
        id: 8,
        title: 'Компьютерные комплектующие',
        uzTitle: 'Kompyuter qismlari',
        img:"/first9.png",
        className: "cctv",
        href: "/catalog/komplektuyushchie",
    },
    {
        id: 9,
        title: 'Периферийные устройства',
        uzTitle: 'Periferik qurilmalar',
        img:"/first10.png",
        className: "cctv",
        href: "/catalog/periferiynye-ustroystva",
    },
  
]

